site_name: Neural Network Distiller
theme: readthedocs
site_description: 'Distiller Documentation by Intel AI'
use_directory_urls: False
site_dir: ../docs
markdown_extensions:
- mdx_math:
    enable_dollar_delimiter: True #for use of inline $..$
- admonition

extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML']
extra_css: [extra.css]


pages:
  - Home: index.md
  - Installation: install.md
  - Usage: usage.md
  - Compression scheduling: schedule.md
  - Compressing models:
    - 'Pruning': 'pruning.md'
    - 'Regularization': 'regularization.md'
    - 'Quantization': 'quantization.md'
    - 'Knowledge Distillation': 'knowledge_distillation.md'
  - Algorithms:
    - Pruning: algo_pruning.md
    - Quantization: algo_quantization.md
  - Model Zoo: model_zoo.md
  - Jupyter notebooks: jupyter.md
  - Design: design.md
